### ISSUE TITLE
Link to organization in event notification

### ISSUE THREAD

**Issue by john-light** [aragonone/notification-service#30]
The email currently says:

> Hi there,
> The following Aragon event you subscribe to happened on mainnet at block #10779208:
> 
> StartVote at Wed Sep 02 2020 02:45:40 GMT+0000 (Coordinated Universal Time) ([see transaction](https://etherscan.io/tx/0x9f7ce1e990fcfa7c2fb98df3a217346c70a2c073cfb3e1a07323d7e7b5ec9943))
> 
> Event values:
> 
> Vote Id: 9
> Creator: 0x1E7547f9353D903FE1448009317Fa9900b47631B
> Metadata:

It would be nice to also add a field like:

> Organization: [cfdao.aragonid.eth](https://client.aragon.org/#/cfdao.aragonid.eth)

replacing the ENS name with the organization address if it does not have an ENS address. This way users can easily and quickly click into the organization where the event occurred and follow up as needed.

**Comment by promaty** [comment]
Would this be fine?

![image](https://user-images.githubusercontent.com/26359933/100395909-2d8ba280-3043-11eb-9907-e248bfaba4d5.png)

No ENS:

![image](https://user-images.githubusercontent.com/26359933/100395947-5875f680-3043-11eb-9eb6-4d9a48fc539c.png)

**Comment by john-light** [comment]
@promaty I like it!

**Comment by promaty** [comment]
Updated
